name: mining_solutions
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  flutter_screenutil: ^5.0.3
  font_awesome_flutter: ^9.2.0
  shared_preferences: ^2.0.13
  cool_alert: ^1.1.0
  flutter_html: ^2.2.1
  intl: ^0.17.0
  shimmer: ^2.0.0
  transparent_image: ^2.0.0
  share_plus: ^4.0.4
  url_launcher: ^6.0.20
  validators: ^3.0.0
  flutter_easyloading: ^3.0.3
  image_picker: ^0.8.4+11
  expandable: ^5.0.1
  settings_ui: ^2.0.2
  skeleton_loader: ^2.0.0+4
  skeletons: ^0.0.3
  cached_network_image: ^3.2.0
  introduction_screen: ^3.0.2
  web_socket_channel: ^2.1.0
  iconsax: ^0.0.7
  badges: ^2.0.2
  figma_squircle: ^0.5.3
  flutter_svg: ^0.22.0
  intl_phone_field: ^3.1.0
  platform: ^3.1.0
  flutter_dotenv: ^5.0.2
  flutter_mapbox_navigation: ^0.0.26
  dio: ^4.0.4
  mapbox_gl: ^0.16.0
  flutter_rating_bar: ^4.0.0
  timelines: ^0.1.0
  expansion_tile_card: ^2.0.0
  keyboard_actions: ^3.4.7
  date_picker_timeline: ^1.2.3
  path_provider: ^2.0.11

  #local_auth: ^2.1.3
  local_auth: ^1.1.7
  open_settings: ^2.0.2
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  google_fonts: 2.2.0
  line_icons: ^2.0.1
  google_nav_bar: ^5.0.5
  provider: ^6.0.2
  pin_code_fields: ^7.3.0
  carousel_slider: ^4.0.0-nullsafety.0
  #google_maps_flutter: ^2.1.1
  google_maps_flutter: ^2.1.8
  google_maps_webservice: ^0.0.20-nullsafety.5
  permission_handler: ^8.3.0
  http: ^0.13.4
  dropdown_button2: ^1.0.7
  lottie: ^1.2.1
  #location: ^4.2.0
  location: ^4.4.0
  geolocator: ^8.0.5
  geocoding: ^2.0.2
  dots_indicator: ^2.0.0
  easy_splash_screen: ^1.0.3
  flutter_launcher_icons: null

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon-hubmine.png"
  adaptive_icon_background: "assets/icon/icon-hubmine.png"

flutter:
  uses-material-design: true

  assets:
    - logo.png
    - hubmine-logo.png
    - check-mark-success.json
    - rectangle-bg-intro-one.png
    - Hubmine.png
    - rectangle-bg-intro-two.png
    - rectangle-bg-intro-three.png
    - LogoSplash.png
    - Logo-Hubmine.png
    - grava.png
    - piedra-caliza.png
    - marker-hubmine.png
    - icon-obra.png
    - icon-casa.png
    - icon-factory.png
    - icon-corporativo.png
    - transportistas_hubmine.jpg
    - default-profile.png
    - user-by-default.png
    - not-notifications.png
    - hubcoin.png
    - hubmine-people.jpg
    - hubmine-soon.png
    - truck-icon.png
    - activate-location-hubmine.png
    - hubmine-icon-mini.png
    - know-hubmine.png
    - compra-express.png
    - nos-vemos-en-obra.png
    - hubmine-icon-name.png
    - agregado.jpeg
    - camion-revolvedor.jpeg
    - maquinaria.jpg
    - arrow_right.svg
    - piedra.jpeg
    - search-normal.svg
    - arrow-left.svg
    - start_search.svg
    - no_search.svg
    - icon-hubmine.png
    - truck.svg
    - cart.svg
    - shop.svg
    - arena4d.jpeg
    - small-arrow-right.svg
    - edit.svg
    - award.svg
    - notification.svg
    - referido.svg
    - settings.svg
    - headphone.svg
    - more.svg
    - logout.svg
    - hubmine.svg
    - waitlist.png
    - small-arrow-down.svg
    - lock.svg
    - eye.svg
    - eye-slash.svg
    - house.svg
    - buliding.svg
    - plant.svg
    - corporate.svg
    - camion-con-grava.jpeg
    - location.svg
    - building.png
    - proveedor.png
    - assets/config/.env
    - dollar-circle.svg

    - truck_n_driver.svg
    - driver.svg
    - calendar-2.svg
    - 3d-square.svg
    - format-square.svg
    - mixer-concrete-hub.svg

    - Onboard-country-select.png
    - Onboard-Best-price.png
    - Onboard-truck.png
    - Onboard-Intro.png

    - EAU.png
    - ecuador.png
    - usa.png
    - mexico.png
    - brazil.png
    - colombia.png
    - spain.png
    - india.png
    - do.png

    - banquetas.png
    - castillos_columnas.png
    - cimentacion.png
    - losa_techo.png
    - pisos.png
    - directo.png

    - order-in-progress.json

    - community.svg
    - calendar.svg
    - bag.svg
    - profile.svg

    - map_location.svg
    - document.svg

flutter_intl:
  enabled: true

  main_locale: es

  class_name: AppLocalizations
